export const GET_POPULAR_LIST_SUCCESS = 'GET_POPULAR_LIST_SUCCESS'
export const GET_POPULAR_LIST_PAGE_TWO_SUCCESS = 'GET_POPULAR_LIST_PAGE_TWO_SUCCESS'
export const GET_LIST_FAILED = 'GET_LIST_FAILED'

export const SEARCH_RESULTS_INIT = 'SEARCH_RESULTS_INIT'
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS'
export const GET_SEARCH_RESULTS_FAILED = 'GET_SEARCH_RESULTS_FAILED'
