export const GET_POPULAR_LIST_SUCCESS = 'GET_POPULAR_LIST_SUCCESS'
export const GET_POPULAR_LIST_PAGE_TWO_SUCCESS = 'GET_POPULAR_LIST_PAGE_TWO_SUCCESS'
export const GET_LIST_FAILED = 'GET_LIST_FAILED'
export const GET_RECOMMENDATION_LIST_SUCCESS = 'GET_RECOMMENDATION_LIST_SUCCESS'
