export const INIT_POPULAR_LIST = 'INIT_POPULAR_LIST'
export const GET_POPULAR_LIST_SUCCESS = 'GET_POPULAR_LIST_SUCCESS'
export const GET_POPULAR_LIST_PAGE_TWO_SUCCESS = 'GET_POPULAR_LIST_PAGE_TWO_SUCCESS'
export const GET_POPULAR_LIST_FAILED = 'GET_POPULAR_LIST_FAILED'
